In [1]:
import numpy as np

In [2]:
mu = np.array([0.06,0.02,0.04],dtype = np.float32)

In [3]:
V = np.array([[8.0,-2.0,4.0],[-2.0,2.0,-2.0],[4.0,-2.0,8.0]],dtype = np.float32)*10**-3

In [4]:
r_f = 0.01

In [5]:
mu

array([0.06, 0.02, 0.04], dtype=float32)

In [6]:
V

array([[ 0.008, -0.002,  0.004],
       [-0.002,  0.002, -0.002],
       [ 0.004, -0.002,  0.008]], dtype=float32)

In [7]:
r_f

0.01

In [10]:
#Q1
x=[1/3,1/3,1/3]

In [11]:
x

[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]

In [12]:
sum(mu*np.array(x))

0.03999999910593033

In [13]:
#q2 volatility
np.sqrt(np.array(x).dot(V).dot(np.array(x).T))

0.044721360612071076

In [27]:
#q3 minimum variance portfolio
V1=np.concatenate((np.concatenate((2*V,np.array([-1,-1,-1]).reshape(-1,1)),axis = 1),np.array([1,1,1,0]).reshape(1,-1)),axis = 0)
V1

array([[ 0.016, -0.004,  0.008, -1.   ],
       [-0.004,  0.004, -0.004, -1.   ],
       [ 0.008, -0.004,  0.016, -1.   ],
       [ 1.   ,  1.   ,  1.   ,  0.   ]])

In [28]:
sol = np.linalg.inv(V1).dot(np.array([0,0,0,1]).T)

In [29]:
sol

array([0.16666667, 0.66666667, 0.16666667, 0.00133333])

In [30]:
x_1 = sol[0:3]
x_1

array([0.16666667, 0.66666667, 0.16666667])

In [31]:
sum(x_1*mu)

0.029999999329447746

In [32]:
#q4
excess_r = mu-r_f
excess_r

array([0.05, 0.01, 0.03], dtype=float32)

In [33]:
Sharpe_opt = np.linalg.inv(V).dot(excess_r.T)/sum(np.linalg.inv(V).dot(excess_r.T))

In [38]:
r_opt = sum(Sharpe_opt*mu)
r_opt

0.03416666807606816

In [43]:
#q5 volatility of sharpe optimal portfolio
volatility=np.sqrt(Sharpe_opt.dot(V).dot(Sharpe_opt.T))
volatility

0.028382314

In [44]:
#q6 slope
slope = (r_opt-r_f)/volatility
slope

0.8514692551779183

In [45]:
#q7 
sigma = 0.05
r_f+slope*sigma

0.05257346275889592